global using MediatR;
global using MicroClean.Application;
global using MicroClean.Extensions;
global using MicroClean.Infrastructure;
global using MicroClean.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;